services:
  # Backend API Service
  - type: web
    name: jifunze-api
    runtime: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: phase-5-group-4-jifunze
    runtime: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://jifunze-31gc.onrender.com
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
