"""Make school_id nullable on users

Revision ID: 8938196f2bb1
Revises: 50aeb98bbd06
Create Date: 2025-09-18 19:50:27.954761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8938196f2bb1'
down_revision = '50aeb98bbd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
