name: Frontend CI

on:
  pull_request:
    branches: [ develop, main ]
    paths: [ 'client/**' ]
  push:
    branches: [ develop, main ]
    paths: [ 'client/**' ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        # `--if-present` avoids error if no lint script exists
        run: npm run lint --if-present

      - name: Run tests
        env:
          CI: true
        run: npm test -- --coverage --watchAll=false

      - name: Build application
        env:
          REACT_APP_API_URL: url_used    # enter the url
        run: npm run build

      - name: Test build
        run: |
          ls -la build/
          test -f build/index.html
          echo "✅ Build successful"
